#!/bin/sh
namespace=default
rm ca-key.pem ca.csr ca.pem consul-key.pem consul.csr consul.pem
kubectl -n $namespace delete statefulset consul
kubectl -n $namespacee delete pvc data-consul-0 data-consul-1 data-consul-2
kubectl -n $namespace delete svc consul
kubectl -n $namespace delete jobs consul-join
kubectl -n $namespace delete secrets consul
kubectl -n $namespace delete configmaps consul
